---
title: "f4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir ="/home/richard/Documents/000_phd_archive/can_res_19")

```

```{r, echo=FALSE}


size<-1e-6

raw <- read.csv('data/mousedata/mousedata.csv')
names(raw) <- c('time','mouse','volume','id')
means<-read.csv('data/mousedata/means.csv')
growthdata <- subset(means,group=='regression')
names(growthdata)[2]<-'id'
rawgrowth <- subset(raw,id=='growth') 
rawreg <- subset(raw,id=="regression")

setwd("data/processedStats")
filelist<-list.files()
filelist<-c("n1_k16_normtest.csv" , "n5_k16_normtest.csv",
            "IFNn1_k16_normtest.csv" , "IFNn5_k16_normtest.csv" )

stats<-lapply(filelist,read.csv,stringsAsFactors=FALSE)
stats <- do.call(rbind,stats)
stats[stats==0]<-NA
stats$condition<-stats$id

stats$condition[stats$condition=="n1_k16_normtest"]<-"-ifn"
stats$condition[stats$condition=="n5_k16_normtest"]<-"-ifn"
stats$condition[stats$condition=="IFNn1_k16_normtest"]<-"+ifn"
stats$condition[stats$condition=="IFNn5_k16_normtest"]<-"+ifn"

stats[stats=="n1_k16_normtest"]<-"n =  1"
stats[stats=="n5_k16_normtest"]<-"n = 5"
stats[stats=="IFNn1_k16_normtest"]<-"n =  1"
stats[stats=="IFNn5_k16_normtest"]<-"n = 5"

```
```{r,echo=FALSE}
require(ggplot2)
require(zoo)
winsize<-30
transfer <- subset(stats,id!='no transfer')
ifn <-subset(transfer,condition=='+ifn')
noifn <-subset(transfer,condition!='+ifn')
# colorblind palette with black:
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

```


```{r, echo=FALSE}
p <- ggplot(ifn,aes(x=time))+
  geom_ribbon(data=stats,aes(x = time, ymin=volmin,ymax=volmax,alpha=0.01,linetype=NA,group=interaction(condition,id)), show.legend = FALSE)+
  geom_line(aes(y=volmed, color=id),size=2)+
    geom_point(data=rawreg,aes(x=time,y=volume*10^6,shape="transfer data"),size=4)+

  scale_x_continuous(name="days after tumour injection",breaks=c(0,2,4,6,8,10,12,14))+
  scale_y_log10(name=bquote('number of tumour cells'),breaks=c(10^3,10^4,10^5,10^6),limits=c(900,2*10^6))+
  scale_colour_manual("id",values=cbbPalette[c(7,6)],labels=c("1 hit","5 hits"))+
  scale_fill_manual("id",values=cbbPalette[c(7,6)],labels=c("1 hit","5 hits"))+
 theme(text = element_text(size=20),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"),legend.title = element_blank(),legend.position=c(0.2,0.80),legend.key = element_blank())
plot(p)

```


```{r, echo=FALSE}


p <- ggplot(ifn,aes(x=time,fill=id, color=id))+
  geom_line(aes(y=rollmean(confracmed,winsize,na.pad=TRUE)),size=1.5)+
  geom_ribbon(aes(x = time, ymin=confracmin,ymax=confracmax,alpha=0.01,linetype=NA), show.legend = FALSE)+
  scale_x_continuous(name="days after tumour injection",limits=c(5,14),breaks=c(6,8,10,12,14))+
  scale_y_continuous(name="CTL conjugate fraction", limits=c(0,1))+
  scale_colour_manual("id",values=cbbPalette[c(7,6)],labels=c("1 hit","5 hits"))+
  scale_fill_manual("id",values=cbbPalette[c(7,6)],labels=c("1 hit","5 hits"))+

 theme(text = element_text(size=20),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"),legend.title = element_blank(),legend.position=c(0.85,0.90),legend.key = element_blank())
plot(p)


```


```{r, echo=FALSE}

p <- ggplot(ifn,aes(x=time,fill=id, color=id))+
  geom_line(aes(y=tcellmed),size=1.5)+
  geom_ribbon(aes(x = time, ymin=tcellmin,ymax=tcellmax,alpha=0.01,linetype=NA), show.legend = FALSE)+
  scale_x_continuous(name="days after tumour injection",breaks=c(6,8,10,12,14),limits=c(5,14))+
  scale_y_log10(name="number of CTLs",breaks=c(10,100,1000,10000),limits=c(8,11000))+
  scale_colour_manual("id",values=cbbPalette[c(7,6)],labels=c("1 hit","5 hits"))+
  scale_fill_manual("id",values=cbbPalette[c(7,6)],labels=c("1 hit","5 hits"))+
 theme(text = element_text(size=20),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"),legend.title = element_blank(),legend.position=c(0.85,0.2),legend.key = element_blank())
plot(p)

```


```{r, echo=FALSE}

p <- ggplot(ifn,aes(x=time,fill=id, color=id))+
  geom_line(aes(y=1440*rollmean(realisedmed,winsize,na.pad=TRUE)),size=1.5)+
  geom_ribbon(aes(x = time, ymin=1440*rollmean(realisedmin,winsize,na.pad=TRUE),ymax=1440*rollmean(realisedmax,winsize,na.pad=TRUE),alpha=0.01,linetype=NA), show.legend = FALSE)+
  scale_x_continuous(name="days after tumour injection",breaks=c(6,8,10,12,14),limits=c(5.5,14))+
    scale_y_continuous(name=bquote('kills CTL' ^-1 ~'day' ^-1))+
      coord_cartesian(ylim=c(5, 18))+
  scale_colour_manual("id",values=cbbPalette[c(7,6)],labels=c("1 hit","5 hits"))+
  scale_fill_manual("id",values=cbbPalette[c(7,6)],labels=c("1 hit","5 hits"))+
 theme(text = element_text(size=20),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"),legend.title = element_blank(),legend.position=c(0.85,0.8),legend.key = element_blank())
plot(p)

p <- ggplot(ifn,aes(x=time,fill=id, color=id))+
  geom_line(aes(y=1440*rollmean(measuredmed,winsize,na.pad=TRUE)),size=1.5)+
  geom_ribbon(aes(x = time, ymin=1440*rollmean(measuredmin,winsize,na.pad=TRUE),
                  ymax=1440*rollmean(measuredmax,winsize,na.pad=TRUE),alpha=0.005,linetype=NA), show.legend = FALSE)+
  scale_x_continuous(name="days after tumour injection",breaks=c(6,8,10,12,14),limits=c(5.5,14))+
    scale_y_continuous(name=bquote('kills conjugated CTL' ^-1 ~'day' ^-1))+
  
    coord_cartesian(ylim=c(5, 25))+
  scale_colour_manual("id",values=cbbPalette[c(7,6)],labels=c("1 hit","5 hits"))+
  scale_fill_manual("id",values=cbbPalette[c(7,6)],labels=c("1 hit","5 hits"))+
 theme(text = element_text(size=20),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"),legend.title = element_blank(),legend.position=c(0.85,0.2),legend.key = element_blank())
plot(p)


```
```{r, echo=FALSE}

day0<-1
range <- 3

onectl<-120

mins <- onectl*day0
maxs <- onectl*(day0+range)

setwd('data/boxAnalysis')
boxFiles <- list.files()
## print conditions to analyse
boxFiles

getHist <- function(file){
boxdata<-read.csv(file)
##print mean killing rate for this data


## exclude data with less than 
boxdata<-boxdata[boxdata$ctl>mins&boxdata$ctl<maxs,]
length(boxdata$time)
boxdata$rate<-1440*boxdata$death/boxdata$ctl
print(1440*sum(boxdata$death)/sum(boxdata$ctl))
print(mean(boxdata$ctl))

boxdata<-boxdata[boxdata$rate<39,]
#boxdata<-boxdata[boxdata$death>0,]
n1hist <- hist(boxdata$rate,breaks=seq(-1,39,8))
return(n1hist)

}

n1_IFN <- getHist(boxFiles[1])
n1_IFN_1 <- data.frame(mids=n1_IFN$mids,counts=n1_IFN$counts,id=rep("one hit",length(n1_IFN$mids)))
n1_IFN <- getHist(boxFiles[2])
n1_IFN_2 <- data.frame(mids=n1_IFN$mids,counts=n1_IFN$counts,id=rep("one hit",length(n1_IFN$mids)))
n1_IFN <- getHist(boxFiles[3])
n1_IFN_3 <- data.frame(mids=n1_IFN$mids,counts=n1_IFN$counts,id=rep("one hit",length(n1_IFN$mids)))

n1_IFN<-rbind(n1_IFN_1,n1_IFN_2,n1_IFN_3)

n5_IFN <- getHist(boxFiles[4])
n5_IFN_1 <- data.frame(mids=n5_IFN$mids,counts=n5_IFN$counts,id=rep("multi hit",length(n5_IFN$mids)))
n5_IFN <- getHist(boxFiles[5])
n5_IFN_2 <- data.frame(mids=n5_IFN$mids,counts=n5_IFN$counts,id=rep("multi hit",length(n5_IFN$mids)))
n5_IFN <- getHist(boxFiles[6])
n5_IFN_3 <- data.frame(mids=n5_IFN$mids,counts=n5_IFN$counts,id=rep("multi hit",length(n5_IFN$mids)))

n5_IFN<-rbind(n5_IFN_1,n5_IFN_2,n5_IFN_3)


focus <- rbind(n1_IFN,n5_IFN)
```

```{r, echo=FALSE}
## 
require(ggplot2)
p <- ggplot(focus,aes(x=mids,y=counts,fill=id,group=id))+
  geom_col(position="dodge")+
    scale_x_continuous(name=bquote('kills conjugated CTL' ^-1 ~'day' ^-1))+
  scale_y_continuous(name="frequency")+
    scale_fill_manual("id",values=cbbPalette[c(6,7)])+
   theme(text = element_text(size=20),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"),legend.title = element_blank(),legend.position=c(0.8,0.80),legend.key = element_blank())
p




```

```{r, echo=FALSE}
require(ggplot2)
setwd("data/stats")
dirs<-list.files()
dirs <- c("IFNn1_k16_normtest","IFNn5_k16_normtest","n1_k16_normtest","n5_k16_normtest")

load.stats <- function(name,dir){
  filename <- paste(dir,name,sep="/")
  stats<-read.csv(filename)
  stats$id<-rep(dir,length(stats$time))
  stats$name<-rep(name,length(stats$time))
  return(stats)
  
}

load.run <- function(dir){
  filenames<-list.files(dir)
stats <- lapply(filenames,load.stats,dir=dir)
stats<-do.call(rbind,stats)
return(stats)
}


stats <- lapply(dirs, load.run)
stats <- do.call(rbind,stats)
stats$deaths<-abs(stats$deaths)
stats$rate<-1440*stats$deaths/stats$con


```
```{r,echo=FALSE}
require(ggplot2)


p <- ggplot(stats,aes(x=time))+

  geom_line(aes(y=volmed, color=id),size=1.5)+
  geom_line(data=odedata,aes(y=volume,color=id),size=1.5,linetype=2)+

  scale_x_continuous(name="days after tumour injection",breaks=c(0,2,4,6,8,10,12,14))+
  scale_y_log10(name=bquote('tumour cells'))+
  # scale_colour_manual("id",values=c("navyblue","darkgreen","red"),labels=c("k =  4","k = 16","no transfer"))+
  #scale_linetype_manual("mode,values=c(1,6),labels=c("k = 4","k = 16","in-vivo data"))+
 theme(text = element_text(size=20),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"),legend.title = element_blank(),legend.position=c(0.2,0.80),legend.key = element_blank())
plot(p)

transfer <- subset(stats,id!='no transfer')

p <- ggplot(transfer,aes(x=time,fill=id, color=id))+
  geom_line(aes(y=conmed/tcellmed),size=1.5)+
  geom_ribbon(aes(x = time, ymin=conmin,ymax=conmax,alpha=0.01,linetype=NA), show.legend = FALSE)+
  scale_x_continuous(name="days after tumour injection",limits=c(5,14),breaks=c(6,8,10,12,14))+
  scale_y_continuous(name="CTL conjugate fraction", limits=c(0,1))+
  scale_colour_manual("id",values=c("navyblue","darkgreen"),labels=c("k =  16","k =  4"))+
  scale_fill_manual("id",values=c("navyblue","darkgreen"),labels=c("k =  16","k =  4"))+

 theme(text = element_text(size=20),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"),legend.title = element_blank(),legend.position=c(0.85,0.90),legend.key = element_blank())
plot(p)

p <- ggplot(transfer,aes(x=time,fill=id, color=id))+
  geom_line(aes(y=tcellmed),size=1.5)+
  #geom_ribbon(aes(x = time, ymin=tmin,ymax=tmax,alpha=0.01,linetype=NA), show.legend = FALSE)+
  scale_x_continuous(name="days after tumour injection",breaks=c(6,8,10,12,14),limits=c(5,14))+
  scale_y_log10(name="CTLs")+
  scale_colour_manual("id",values=c("navyblue","darkgreen"),labels=c("k =  16","k =  4"))+
  scale_fill_manual("id",values=c("navyblue","darkgreen"),labels=c("k =  16","k =  4"))+
 theme(text = element_text(size=20),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"),legend.title = element_blank(),legend.position=c(0.15,0.85),legend.key = element_blank())
plot(p)

p <- ggplot(transfer,aes(x=time,fill=id, color=id))+
  geom_line(aes(y=1440*deathmed/conmed),size=0.5)+
  geom_ribbon(aes(x = time, ymin=deathmin/conmed,ymax=deathmax/conmed,alpha=0.01,linetype=NA), show.legend = FALSE)+
  scale_x_continuous(name="days after tumour injection",breaks=c(6,8,10,12,14),limits=c(5,14))+
  scale_y_continuous(name="realised",limits=c(0,40))+
  scale_colour_manual("id",values=c("navyblue","darkgreen"),labels=c("k =  16","k =  4"))+
  scale_fill_manual("id",values=c("navyblue","darkgreen"),labels=c("k =  16","k =  4"))+
 theme(text = element_text(size=20),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"),legend.title = element_blank(),legend.position=c(0.15,0.85),legend.key = element_blank())
plot(p)


```






```{r, echo=FALSE}
library(ggplot2)

ifndf <- subset(plotdf,id=="IFNn1" | id=="IFNn5")
ndf <- subset(plotdf,id=="n1" | id=="n5")

plt <- ggplot(data=ifndf,aes(x=rad,y=rate,color=id))+
  geom_point(alpha=0.5,size=2)+
  scale_y_continuous(limits=c(0,40))
print(plt)

plt <- ggplot(data=ndf,aes(x=rad,y=rate,color=id))+
  geom_point(alpha=0.5,size=2)+
  scale_y_continuous(limits=c(0,40))
print(plt)
```

